import MobileNav from "@/components/MobileNav";
import type { Metadata } from "next";
import { Figtree, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const figtreeMono = Figtree({
  variable: "--font-figtree-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${figtreeMono.variable} antialiased `}
      >
        <Navbar />
        <MobileNav />
        {children}
      </body>
    </html>
  );
}
